[package]
name = "fluent_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.25"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
config = "0.14.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.116"
