[target.x86_64-unknown-linux-gnu]
image = "sciolence/cross-rs-custom-x86_64-unknown-linux-gnu:latest"
[target.x86_64-pc-windows-msvc]
image = "idhyt/cross-rs-x86_64-pc-windows-msvc:0.2.5"
[target.x86_64h-apple-darwin]
image = "idhyt/cross-rs-x86_64-apple-darwin:0.0.1"

