[package]
name = "fluent"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/fluent-cli",
    "crates/fluent-core",
    "crates/fluent-engines",
    "crates/fluent-storage",
]

[dependencies]
fluent-cli = { path = "crates/fluent-cli" }
fluent-core = { path = "crates/fluent-core" }
fluent-engines = { path = "crates/fluent-engines" }
fluent-storage = { path = "crates/fluent-storage" }

tokio = { version = "1", features = ["full"] }
clap = { version = "4.5.8", features = ["derive"] }
anyhow = "1.0"
env_logger = "0.11.3"

neo4rs = "0.7.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.3", features = ["v4", "serde"] }
