# crates/fluent-core/Cargo.toml
[package]
name = "fluent-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
serde_json = "1.0.120"
async-trait = "0.1.80"
log = "0.4.22"
chrono = "0.4.38"
uuid = { version = "1.9.1", features = ["v4"] }
neo4rs = "0.7.1"
reqwest = { version = "0.12.5", features = ["json"] }
unicode-segmentation = "1.11.0"


#rust-bert = {  version = "0.18.0"  }
tokenizers = "0.14.0"
rust-stemmers = "1.2.0"
stop-words = "0.8.0"
base64 = "0.22.1"
tokio = "1.38.0"
regex = "1.10.5"
url = "2.5.2"
termimad = "0.29.2"
crossterm = "0.27.0"
syntect = "5.2.0"
indicatif = "0.17.8"
owo-colors = "3.5.0"