# crates/fluent-engines/Cargo.toml
[package]
name = "fluent-engines"
version = "0.1.0"
edition = "2021"

[dependencies]
fluent-core = { path = "../fluent-core" }
reqwest = { version = "0.12.5", default-features = false, features = [
    "json",
    "stream",
    "multipart",
    "rustls-tls",
] }
serde_json = "1.0.120"
anyhow = "1.0.86"
async-trait = "0.1.80"
log = "0.4.22"
tokio = "1.38.0"
tokio-util = "0.7.11"
base64 = "0.22.1"
mime_guess = "2.0.3"
serde = { version = "1.0.204", features = ["derive"] }
uuid = "1.9.1"
futures-util = "0.3.30"
tempfile = "3.10.1"
futures = "0.3.30"
strum = { version = "0.26.3", features = ["derive"] }


#indicatif = "0.17.8"
#clap = "4.5.8"
