name: Build Rust Projects with Cross
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target: x86_64-unknown-freebsd
            bin: precious
            filename: precious-FreeBSD-x86_64.tar.gz
            command: build

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: precious.exe
            filename: precious-Windows-x86_64.zip
            command: both

          - os: macOS-latest
            target: x86_64-apple-darwin
            bin: precious
            filename: precious-Darwin-x86_64.tar.gz
            command: both

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Cargo environment
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Change to Project Directory
        run: cd fluent_cli/
        
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.command }}
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true
